[package]
name = "scaffold"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true}
colored ={ workspace = true }
common ={ path = "../common" }
args = { path = "../args"}
commands = { path = "../commands"}