[workspace]
members  = ["crates/*"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.0", features = ["derive"] }
dialoguer = "0.11.0"
handlebars = "6.3.0"
fs_extra = "1.3"
walkdir = "2.3"
colored = "3.0.0"
anyhow = "1.0"
thiserror = "2.0.11"
lazy_static = "1.4.0"